[[tasks]]
command = "cargo fmt"

[[tasks]]
command = "cargo clippy -- -Dwarnings"
env = {}

[[tasks]]
env = { RUST_BACKTRACE = "1" }
command = "cargo test"

[[tasks]]
env = { Y = "a", X = "2" }
command = "bash test.sh"
